# Generated by Django 5.2.6 on 2025-10-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='paciente_confirmou_presenca',
            field=models.BooleanField(default=False, help_text="Indica se o paciente clicou em 'Confirmar Presença'", verbose_name='Presença Confirmada pelo Paciente'),
        ),
    ]
