# Generated by Django 5.2.6 on 2025-10-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_consulta_paciente_confirmou_presenca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('aguardando_remarcacao', 'Aguardando Remarcação'), ('cancelada', 'Cancelada'), ('realizada', 'Realizada')], default='pendente', max_length=25, verbose_name='Status'),
        ),
    ]
